services:
  # Backend configuration
  - type: web
    name: namami-gaiya-backend
    env: node
    buildCommand: "cd backend && npm install"
    startCommand: "cd backend && npm start"
    envVars:
      - key: PORT
        value: 5000

  # Frontend configuration
  - type: web
    name: namami-gaiya-frontend
    env: static
    buildCommand: "cd frontend && npm install && npm run build"
    staticPublishPath: frontend/dist
    routes:
      - type: rewrite
        source: /admin/*
        destination: /index.html
      - type: rewrite
        source: /influencer-program
        destination: /index.html
      # General fallback for any other subroutes
      - type: rewrite
        source: /((?!api|uploads|static).*)
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        value: https://namami.onrender.com # Confirmed by user as correct backend URL
